version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: car_system_db
    environment:
      POSTGRES_DB: car_system
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - car_network

  backend:
    build: ./backend
    container_name: car_system_api
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/car_system
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    networks:
      - car_network
    volumes:
      - ./backend:/app
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

  frontend:
    build: ./frontend
    container_name: car_system_frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - car_network
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=http://localhost:8000
    command: npm run dev

volumes:
  postgres_data:

networks:
  car_network:
    driver: bridge
